use std::cmp::Ordering;
use std::fmt;

#[derive(Clone, Debug)]
pub struct Token {
  val: String,
  t_type: TokenType,
  start: usize,
  end: usize,
}

impl Token {
  pub fn new(val: String, t: TokenType, start: usize, end: usize) -> Token {
    Token {
      val: val,
      t_type: t,
      start: start,
      end: end,
    }
  }

  pub fn get_type(&self) -> &TokenType {
    &self.t_type
  }

  pub fn get_value(&self) -> &String {
    &self.val
  }

  pub fn get_start(&self) -> &usize {
    &self.start
  }

  pub fn get_end(&self) -> &usize {
    &self.end
  }
}

impl fmt::Display for Token {
  fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
    write!(
      f,
      "type: {:?}, text: {}, start: {}, end: {}",
      self.t_type, self.val, self.start, self.end
    )
  }
}

impl PartialOrd for Token {
  fn partial_cmp(&self, other: &Self) -> Option<Ordering> {
    Some(self.cmp(other))
  }
}

impl Ord for Token {
  fn cmp(&self, other: &Self) -> Ordering {
    self.start.cmp(&other.start)
  }
}

impl Eq for Token {}

impl PartialEq for Token {
  fn eq(&self, other: &Self) -> bool {
    self.start == other.start && self.val == other.val
  }
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub enum TokenType {
  Identifier,
  Number,
  HexNumber,
  BinNumber,
  DecNumber,
  DirectiveA16,
  DirectiveA8,
  DirectiveAddr,
  DirectiveAddrsize,
  DirectiveAlign,
  DirectiveAnd,
  DirectiveAsciiz,
  DirectiveAsize,
  DirectiveAssert,
  DirectiveAutoimport,
  DirectiveBank,
  DirectiveBankbyte,
  DirectiveBankbytes,
  DirectiveBitand,
  DirectiveBitnot,
  DirectiveBitor,
  DirectiveBitxor,
  DirectiveBlank,
  DirectiveBss,
  DirectiveByt,
  DirectiveByte,
  DirectiveCase,
  DirectiveCharmap,
  DirectiveCode,
  DirectiveConcat,
  DirectiveCondes,
  DirectiveConst,
  DirectiveConstructor,
  DirectiveCpu,
  DirectiveData,
  DirectiveDbg,
  DirectiveDbyt,
  DirectiveDebuginfo,
  DirectiveDef,
  DirectiveDefine,
  DirectiveDefined,
  DirectiveDefinedmacro,
  DirectiveDelmac,
  DirectiveDelmacro,
  DirectiveDestructor,
  DirectiveDword,
  DirectiveElse,
  DirectiveElseif,
  DirectiveEnd,
  DirectiveEndenum,
  DirectiveEndif,
  DirectiveEndmac,
  DirectiveEndmacro,
  DirectiveEndproc,
  DirectiveEndrep,
  DirectiveEndrepeat,
  DirectiveEndscope,
  DirectiveEndstruct,
  DirectiveEndunion,
  DirectiveEnum,
  DirectiveError,
  DirectiveExitmac,
  DirectiveExitmacro,
  DirectiveExport,
  DirectiveExportzp,
  DirectiveFaraddr,
  DirectiveFatal,
  DirectiveFeature,
  DirectiveFileopt,
  DirectiveFopt,
  DirectiveForceimport,
  DirectiveForceword,
  DirectiveGlobal,
  DirectiveGlobalzp,
  DirectiveHibyte,
  DirectiveHibytes,
  DirectiveHiword,
  DirectiveI16,
  DirectiveI8,
  DirectiveIdent,
  DirectiveIf,
  DirectiveIfblank,
  DirectiveIfconst,
  DirectiveIfdef,
  DirectiveIfnblank,
  DirectiveIfnconst,
  DirectiveIfndef,
  DirectiveIfnref,
  DirectiveIfp02,
  DirectiveIfp4510,
  DirectiveIfp816,
  DirectiveIfpc02,
  DirectiveIfpsc02,
  DirectiveIfref,
  DirectiveImport,
  DirectiveImportzp,
  DirectiveIncbin,
  DirectiveInclude,
  DirectiveInterruptor,
  DirectiveIsize,
  DirectiveIsmnem,
  DirectiveIsmnemonic,
  DirectiveLeft,
  DirectiveLinecont,
  DirectiveList,
  DirectiveListbytes,
  DirectiveLobyte,
  DirectiveLobytes,
  DirectiveLocal,
  DirectiveLocalchar,
  DirectiveLoword,
  DirectiveMac,
  DirectiveMacpack,
  DirectiveMacro,
  DirectiveMatch,
  DirectiveMax,
  DirectiveMid,
  DirectiveMin,
  DirectiveMod,
  DirectiveNot,
  DirectiveNull,
  DirectiveOr,
  DirectiveOrg,
  DirectiveOut,
  DirectiveP02,
  DirectiveP4510,
  DirectiveP816,
  DirectivePagelen,
  DirectivePagelength,
  DirectiveParamcount,
  DirectivePc02,
  DirectivePopcpu,
  DirectivePopseg,
  DirectiveProc,
  DirectivePsc02,
  DirectivePushcpu,
  DirectivePushseg,
  DirectiveRef,
  DirectiveReferenced,
  DirectiveReloc,
  DirectiveRepeat,
  DirectiveRes,
  DirectiveRight,
  DirectiveRodata,
  DirectiveScope,
  DirectiveSegment,
  DirectiveSet,
  DirectiveSetcpu,
  DirectiveShl,
  DirectiveShr,
  DirectiveSizeof,
  DirectiveSmart,
  DirectiveSprintf,
  DirectiveStrat,
  DirectiveString,
  DirectiveStrlen,
  DirectiveStruct,
  DirectiveTag,
  DirectiveTcount,
  DirectiveTime,
  DirectiveUndef,
  DirectiveUndefine,
  DirectiveUnion,
  DirectiveVersion,
  DirectiveWarning,
  DirectiveWord,
  DirectiveXmatch,
  DirectiveXor,
  DirectiveZeropage,
  LocalLabel,
  XRegister,
  YRegister,
  Comment,
  Whitespace,
  Addition,
  Subtraction,
  Multiplication,
  Division,
  Assignment,
  Equal,
  Xor,
  Or,
  And,
  Comma,
  Colon,
  Hash,
  OParen,
  CParen,
  OCurly,
  CCurly,
  OBracket,
  CBracket,
  LessThan,
  LessThanOrEqual,
  GreaterThan,
  GreaterThanOrEqual,
  Not,
  Shl,
  Shr,
  BoolNot,
  StringConst,
  Newline,
  Namespace,
  ULabel,
  EndOfFile,
}

impl TokenType {
  pub fn get_directive_type(identifier: &str) -> TokenType {
    match identifier {
      "a16" => TokenType::DirectiveA16,
      "a8" => TokenType::DirectiveA8,
      "addr" => TokenType::DirectiveAddr,
      "addrsize" => TokenType::DirectiveAddrsize,
      "align" => TokenType::DirectiveAlign,
      "and" => TokenType::DirectiveAnd,
      "asciiz" => TokenType::DirectiveAsciiz,
      "asize" => TokenType::DirectiveAsize,
      "assert" => TokenType::DirectiveAssert,
      "autoimport" => TokenType::DirectiveAutoimport,
      "bank" => TokenType::DirectiveBank,
      "bankbyte" => TokenType::DirectiveBankbyte,
      "bankbytes" => TokenType::DirectiveBankbytes,
      "bitand" => TokenType::DirectiveBitand,
      "bitnot" => TokenType::DirectiveBitnot,
      "bitor" => TokenType::DirectiveBitor,
      "bitxor" => TokenType::DirectiveBitxor,
      "blank" => TokenType::DirectiveBlank,
      "bss" => TokenType::DirectiveBss,
      "byt" => TokenType::DirectiveByt,
      "byte" => TokenType::DirectiveByte,
      "case" => TokenType::DirectiveCase,
      "charmap" => TokenType::DirectiveCharmap,
      "code" => TokenType::DirectiveCode,
      "concat" => TokenType::DirectiveConcat,
      "condes" => TokenType::DirectiveCondes,
      "const" => TokenType::DirectiveConst,
      "constructor" => TokenType::DirectiveConstructor,
      "cpu" => TokenType::DirectiveCpu,
      "data" => TokenType::DirectiveData,
      "dbg" => TokenType::DirectiveDbg,
      "dbyt" => TokenType::DirectiveDbyt,
      "debuginfo" => TokenType::DirectiveDebuginfo,
      "def" => TokenType::DirectiveDef,
      "define" => TokenType::DirectiveDefine,
      "defined" => TokenType::DirectiveDefined,
      "definedmacro" => TokenType::DirectiveDefinedmacro,
      "delmac" => TokenType::DirectiveDelmac,
      "delmacro" => TokenType::DirectiveDelmacro,
      "destructor" => TokenType::DirectiveDestructor,
      "dword" => TokenType::DirectiveDword,
      "else" => TokenType::DirectiveElse,
      "elseif" => TokenType::DirectiveElseif,
      "end" => TokenType::DirectiveEnd,
      "endenum" => TokenType::DirectiveEndenum,
      "endif" => TokenType::DirectiveEndif,
      "endmac" => TokenType::DirectiveEndmac,
      "endmacro" => TokenType::DirectiveEndmacro,
      "endproc" => TokenType::DirectiveEndproc,
      "endrep" => TokenType::DirectiveEndrep,
      "endrepeat" => TokenType::DirectiveEndrepeat,
      "endscope" => TokenType::DirectiveEndscope,
      "endstruct" => TokenType::DirectiveEndstruct,
      "endunion" => TokenType::DirectiveEndunion,
      "enum" => TokenType::DirectiveEnum,
      "error" => TokenType::DirectiveError,
      "exitmac" => TokenType::DirectiveExitmac,
      "exitmacro" => TokenType::DirectiveExitmacro,
      "export" => TokenType::DirectiveExport,
      "exportzp" => TokenType::DirectiveExportzp,
      "faraddr" => TokenType::DirectiveFaraddr,
      "fatal" => TokenType::DirectiveFatal,
      "feature" => TokenType::DirectiveFeature,
      "fileopt" => TokenType::DirectiveFileopt,
      "fopt" => TokenType::DirectiveFopt,
      "forceimport" => TokenType::DirectiveForceimport,
      "forceword" => TokenType::DirectiveForceword,
      "global" => TokenType::DirectiveGlobal,
      "globalzp" => TokenType::DirectiveGlobalzp,
      "hibyte" => TokenType::DirectiveHibyte,
      "hibytes" => TokenType::DirectiveHibytes,
      "hiword" => TokenType::DirectiveHiword,
      "i16" => TokenType::DirectiveI16,
      "i8" => TokenType::DirectiveI8,
      "ident" => TokenType::DirectiveIdent,
      "if" => TokenType::DirectiveIf,
      "ifblank" => TokenType::DirectiveIfblank,
      "ifconst" => TokenType::DirectiveIfconst,
      "ifdef" => TokenType::DirectiveIfdef,
      "ifnblank" => TokenType::DirectiveIfnblank,
      "ifnconst" => TokenType::DirectiveIfnconst,
      "ifndef" => TokenType::DirectiveIfndef,
      "ifnref" => TokenType::DirectiveIfnref,
      "ifp02" => TokenType::DirectiveIfp02,
      "ifp4510" => TokenType::DirectiveIfp4510,
      "ifp816" => TokenType::DirectiveIfp816,
      "ifpc02" => TokenType::DirectiveIfpc02,
      "ifpsc02" => TokenType::DirectiveIfpsc02,
      "ifref" => TokenType::DirectiveIfref,
      "import" => TokenType::DirectiveImport,
      "importzp" => TokenType::DirectiveImportzp,
      "incbin" => TokenType::DirectiveIncbin,
      "include" => TokenType::DirectiveInclude,
      "interruptor" => TokenType::DirectiveInterruptor,
      "isize" => TokenType::DirectiveIsize,
      "ismnem" => TokenType::DirectiveIsmnem,
      "ismnemonic" => TokenType::DirectiveIsmnemonic,
      "left" => TokenType::DirectiveLeft,
      "linecont" => TokenType::DirectiveLinecont,
      "list" => TokenType::DirectiveList,
      "listbytes" => TokenType::DirectiveListbytes,
      "lobyte" => TokenType::DirectiveLobyte,
      "lobytes" => TokenType::DirectiveLobytes,
      "local" => TokenType::DirectiveLocal,
      "localchar" => TokenType::DirectiveLocalchar,
      "loword" => TokenType::DirectiveLoword,
      "mac" => TokenType::DirectiveMac,
      "macpack" => TokenType::DirectiveMacpack,
      "macro" => TokenType::DirectiveMacro,
      "match" => TokenType::DirectiveMatch,
      "max" => TokenType::DirectiveMax,
      "mid" => TokenType::DirectiveMid,
      "min" => TokenType::DirectiveMin,
      "mod" => TokenType::DirectiveMod,
      "not" => TokenType::DirectiveNot,
      "null" => TokenType::DirectiveNull,
      "or" => TokenType::DirectiveOr,
      "org" => TokenType::DirectiveOrg,
      "out" => TokenType::DirectiveOut,
      "p02" => TokenType::DirectiveP02,
      "p4510" => TokenType::DirectiveP4510,
      "p816" => TokenType::DirectiveP816,
      "pagelen" => TokenType::DirectivePagelen,
      "pagelength" => TokenType::DirectivePagelength,
      "paramcount" => TokenType::DirectiveParamcount,
      "pc02" => TokenType::DirectivePc02,
      "popcpu" => TokenType::DirectivePopcpu,
      "popseg" => TokenType::DirectivePopseg,
      "prog" => TokenType::DirectiveProc,
      "psc02" => TokenType::DirectivePsc02,
      "pushcpu" => TokenType::DirectivePushcpu,
      "pushseg" => TokenType::DirectivePushseg,
      "ref" => TokenType::DirectiveRef,
      "referenced" => TokenType::DirectiveReferenced,
      "reloc" => TokenType::DirectiveReloc,
      "repeat" => TokenType::DirectiveRepeat,
      "res" => TokenType::DirectiveRes,
      "right" => TokenType::DirectiveRight,
      "rodata" => TokenType::DirectiveRodata,
      "scope" => TokenType::DirectiveScope,
      "segment" => TokenType::DirectiveSegment,
      "set" => TokenType::DirectiveSet,
      "setcpu" => TokenType::DirectiveSetcpu,
      "shl" => TokenType::DirectiveShl,
      "shr" => TokenType::DirectiveShr,
      "sizeof" => TokenType::DirectiveSizeof,
      "smart" => TokenType::DirectiveSmart,
      "sprintf" => TokenType::DirectiveSprintf,
      "strat" => TokenType::DirectiveStrat,
      "string" => TokenType::DirectiveString,
      "strlen" => TokenType::DirectiveStrlen,
      "struct" => TokenType::DirectiveStruct,
      "tag" => TokenType::DirectiveTag,
      "tcount" => TokenType::DirectiveTcount,
      "time" => TokenType::DirectiveTime,
      "undef" => TokenType::DirectiveUndef,
      "undefine" => TokenType::DirectiveUndefine,
      "union" => TokenType::DirectiveUnion,
      "version" => TokenType::DirectiveVersion,
      "warning" => TokenType::DirectiveWarning,
      "word" => TokenType::DirectiveWord,
      "xmatch" => TokenType::DirectiveXmatch,
      "xor" => TokenType::DirectiveXor,
      "zeropage" => TokenType::DirectiveZeropage,
      _ => panic!("{} is not a directive", identifier),
    }
  }
}
